### ISSUE TITLE
Phase synchronizing multiple plutos

### ISSUE THREAD

**Issue by Argonghost** [ADolbyB/sdr-beamforming#4]
Hi,

Ive been exploring different methods to do phase synchronizing with multple pluto SDR's and i came across your page.  Would your described cross correlation method for multiple pluto's that are fed with a common external clock?

I program pluto using ```libiio``` in C actually and i was thinking that using your method in a separate thread would be a good idea.
your advise is appreciated.

sincerely,

**Comment by ADolbyB** [comment]
Hello, thanks for the interest. I have been away for a few days doing research.
We needed an external clock to frequency-sync. That still won't phase-sync all channels.

We grabbed this clock module: https://www.ti.com/tool/CDCLVC1310-EVM, however, it comes with a 25MHz clock. This is supposed to be supported by the Pluto, but we have found that this does not work.

We swapped out the crystal for a 40 MHz oscillator and we can confirm this works for frequency-sync. We are not finished with the phase synchronization.

**Comment by Argonghost** [comment]
> Hello, thanks for the interest. I have been away for a few days doing research.
> 
> We needed an external clock to frequency-sync. That still won't phase-sync all channels.
> 
> 
> 
> We grabbed this clock module: https://www.ti.com/tool/CDCLVC1310-EVM, however, it comes with a 25MHz clock. This is supposed to be supported by the Pluto, but we have found that this does not work.
> 
> 
> 
> We swapped out the crystal for a 40 MHz oscillator and we can confirm this works for frequency-sync. We are not finished with the phase synchronization.

 Hi! 
Thanks for your response.  Ok perfect,  im actually working on this exactly,  im using leo bodnar GPSDO, and im trying out cross correlation methods.  Definitely looking forward to your page updates to learn !

**Comment by Argonghost** [comment]
hi @ADolbyB 

I hope this post finds you well.  Is there any update for pluto phase synchronization??
