### ISSUE TITLE
GNU_Radio_Version

### ISSUE THREAD

**Issue by Devyash29** [ADolbyB/sdr-beamforming#5]
Hello, sir which version of GNU Radio you've used for pluto_sdr?

**Comment by ADolbyB** [comment]
> Hello, sir which version of GNU Radio you've used for pluto_sdr?

Hello,

We are running GNU Radio v3.10.7.0, which is the latest version for Ubuntu 22.04 per their website. We have had to fire up older versions for testing old repos, but that was only temporary.

I will quickly note that if you are using a PlutoSDR with the 2 channel Rx, 2 channel Tx modification then make sure you use the `FMComms2/3/4` Sink and Source blocks to access all the channels. We should have known that a little sooner.

Hope that helps,

-- Joel

**Comment by Devyash29** [comment]
Sure sir , Thank you!
