### ISSUE TITLE
Setup with Unknown Transmitter 

### ISSUE THREAD

**Issue by Devyash29** [ADolbyB/sdr-beamforming#6]
Hello sir, I have been working on the Pluto_beamforming code for a few days now. I have tested the system, but I want to try it out with an unknown transmitter. Have you ever tested the same setup with an unknown transmitter? I am facing some issues while testing it with an unknown transmitter.

**Comment by ADolbyB** [comment]
Hello, 

Thanks for your interest. We are still under development here. That is something we are working on.

-- Joel
